### ISSUE TITLE
Idéia para o Botão "Get Direction"

### ISSUE THREAD

**Issue by kauevestena** [FelipeSBarros/foss4g_template#34]
Ao invés de apontar pra feição no OSM (acho que onde o endereço se encontra escrito poderia ter esse link pra feição, já que se refere ao "ponto"), poderia apontar pras coordenadas no geohack: https://geohack.toolforge.org/geohack.php?pagename=Hangar_(centro_de_conven%C3%A7%C3%B5es)&params=1_25_18_S_48_27_22_W

que aí o usuário tem o link e com o [GEO URI](geo:1.7,-48.75) ser conduzido devidamente à obtenção de direções, no app de preferência.

![image](https://github.com/FelipeSBarros/foss4g_template/assets/1434036/432b22c3-d7b8-45db-8b74-9523419cf568)

Incluso, acho que seria bacana traduzir a página da Venue na wikipédia pro inglês!

**Comment by FelipeSBarros** [comment]
Me parece perfeito.
Mete bronca!
