### ISSUE TITLE
Alterar e edicionar redes sociais

### ISSUE THREAD

**Issue by FelipeSBarros** [FelipeSBarros/foss4g_template#5]
Alterar e adicionar redes sociais:

https://github.com/FelipeSBarros/foss4g_template/blob/f2c635ec9c5b971461ba95e829d10b6c638648e9/hugo.toml#L282-L306C56

**Comment by sidneysgoveia** [comment]
Eu fiz as alterações, colocando os novos links (quando existirem).

**Comment by FelipeSBarros** [comment]
Perfeito, @sidneysgoveia . Vi que não haviam outros pontos na página com configuração de redes sociais.
Já está na main.
